### ISSUE TITLE
Create solutions module for Company Kata

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections-kata#104]
There exists no solutions module for the company kata today. Follow the model for the solutions model currently checked in for the Pet Kata.

**Start out by checking in unfinished tests for each exercise**. Solutions for each exercise should be separate pull requests. This will allow multiple developers to potentially complete them.

**Comment by prathasirisha** [comment]
@donraab this issue can be closed.

**Comment by nikhilnanivadekar** [comment]
The issues can be auto closed by making sure that the commits have a Closes tag. It also helps show a trail. That is one of the checks which I do each time I merge a commit.

**Comment by prathasirisha** [comment]
This is good to know. Thanks @nikhilnanivadekar 
I will do so for my next commit and make it point to check for when I am reviewing PRs.
