### ISSUE TITLE
Update Exercise solutions link for company-kata to EC kata slides 

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections-kata#123]
Add solutions links to [Company kata slides](http://eclipse.github.io/eclipse-collections-kata/company-kata/#/2)

**Comment by donraab** [comment]
We could just have one issue for all of the solutions.

**Comment by nikhilnanivadekar** [comment]
Why add any solutions to the slides? We should just have a placeholder at the start or in read me.

**Comment by donraab** [comment]
We currently have slides at the end of each section that link to the solutions. This is just correcting the links to the new solutions so we can delete the branch.

**Comment by nikhilnanivadekar** [comment]
Ah! Got it! I for some reason thought porting over all the code of solutions

**Comment by prathasirisha** [comment]
Updated issue description based your comments.

**Comment by donraab** [comment]
Ok, thanks for volunteering @ScottBNYM! I assigned the ticket to you.
