### ISSUE TITLE
Reference candy-kata in the README

### ISSUE THREAD

**Issue by rinatigati** [eclipse/eclipse-collections-kata#133]
The [Work on Kata Exercises](https://github.com/eclipse/eclipse-collections-kata#work-on-kata-exercises) section of the README mentions the other 2 katas in the repo, but makes no mention of the [candy-kata](https://github.com/eclipse/eclipse-collections-kata/tree/master/candy-kata).

Candy-kata should be referenced alongside the other katas in the README.

**Comment by mvdietz** [comment]
I would like to work on this.

**Comment by donraab** [comment]
Thanks for volunteering @mvdietz. I've assigned the issue to you.

**Comment by prathasirisha** [comment]
@donraab - can you please close this issue.

**Comment by nikhilnanivadekar** [comment]
We should have the commit messages have Fixes. So that we don’t have manually close it.
