### ISSUE TITLE
Add README to pet-kata

### ISSUE THREAD

**Issue by rinatigati** [eclipse/eclipse-collections-kata#136]
[Pet kata](https://github.com/eclipse/eclipse-collections-kata/tree/master/pet-kata) doesn't currently have a README. A README that describes the domain of the pet kata and has links to the appropriate [slides.md](https://github.com/eclipse/eclipse-collections-kata/blob/master/docs/pet-kata/slides.md) for the kata could be very helpful.

There could be a link to this README in the main repo README so that it's easier to navigate to and read about the pet kata.

**Comment by donraab** [comment]
Thanks for creating this issue @rinatigati, I'm going to get started and add a basic readme for the Pet Kata today.
