### ISSUE TITLE
Add README to candy-kata

### ISSUE THREAD

**Issue by rinatigati** [eclipse/eclipse-collections-kata#137]
[Candy kata](https://github.com/eclipse/eclipse-collections-kata/tree/master/candy-kata) doesn't currently have a README. A README that describes the domain of the candy kata would be very helpful.

There could be a link to this README in the main repo README so that it's easier to navigate to and read about the candy kata.

**Comment by pluong** [comment]
I'll take this if no one else is :).

**Comment by donraab** [comment]
Sounds good to me. Thanks for volunteering @pluong !
