### ISSUE TITLE
Do we need `var` in the Kata?

### ISSUE THREAD

**Issue by nikhilnanivadekar** [eclipse/eclipse-collections-kata#153]
Since Eclipse Collections is compatible with Java 8, the Kata should work with Java 8 as well. If we want to use features of versions higher than Java 8 we might want to have a separate module for it. The reason for this is two fold:

1) Incorrect impression of users that Java 11 is required to use the library
2) For the majority of folks who are in Java 8, it means setting up their environment for Java 11 to use the Kata

Thoughts?

**Comment by donraab** [comment]
Showing that Eclipse Collections works fine with JDK 11 via the Kata has benefits of its own, even though it works with Java 8+.

https://wiki.openjdk.java.net/display/quality/Quality+Outreach

1. We can clarify this is not the case. I think we should add the Java 8+ dependency to the [README](https://github.com/eclipse/eclipse-collections/blob/master/README.md) in Eclipse Collections.
2. This is true. Java 8 is 6.5 years old, and Java 11, is soon to be 2 years old and 4 major versions behind the current major release.

To your original question, using `var` in the kata helps simplify the exercises by hiding unnecessarily verbose types for expected values. It's also a good way to have developers experience using new language features with Eclipse Collections types.

**Comment by nikhilnanivadekar** [comment]
For Quality Outreach program we have automated builds which proves that the library works fine.

I am afraid that folks will think that, the library needs Java 11 to work. I am still on Java 8, I am not going to try it out.

I think we should have a Java 8 module and a Java 11 module. 

I follow your point about the version being legacy but isn’t Java 8 where majority of the Java apps are?

The variable verbosity actually helps figure out the types. For me personally var hurts more than helps in this case. 
But I might be the only one.
If keeping the var and Java 11 is the consensus, I am fine with it.

Thoughts  @mohrezaei @motlin ?

**Comment by motlin** [comment]
I agree with @nikhilnanivadekar. First, I've never heard of anyone using a version of Java other than an LTS release. At work we'll go straight from Java 11 to 17 when the time is right. Java 8 was a compelling release, so essentially everyone uses either Java 8 or 11 in 2020. Low-level libraries like slf4j, guava, ours, and many others all use Java 8. It's hard to put myself in someone else's shoes, but to me, it would be surprising to see any collections framework use the most recent LTS.

Does using `var` in the kata imply that Eclipse Collections requires Java 11? Not necessarily. But I don't see how it improves clarity. We switched to var in places like `var people = new ArrayList<Person>();` where the old type was `List` and the new type is `ArrayList`. I think this is the only feature we're using from Java 11. If that's right, I think it makes sense to use Java 8.

**Comment by donraab** [comment]
I've recently been doing live coding with the Eclipse Collections Kata. Using the var keyword in the expected values allows me to quickly demonstrate some things with less keystrokes.

For instance:

```
@Test
public void getCustomerNames()
{
    Function<Customer, String> nameFunction = Customer::getName;
    MutableList<String> customerNames = null;  // this.company.getCustomers()...

    var expectedNames = Lists.mutable.with("Fred", "Mary", "Bill");
    Assert.assertEquals(expectedNames, customerNames);
}
```
can be written as:
```
@Test
public void getCustomerNames()
{
    Function<Customer, String> nameFunction = Customer::getName;
    MutableList<String> customerNames = null;  // this.company.getCustomers()...

    var expectedNames = Lists.immutable.with("Fred", "Mary", "Bill");
    Assert.assertEquals(expectedNames, customerNames);
}
```
can also be written as:
```
@Test
public void getCustomerNames()
{
    Function<Customer, String> nameFunction = Customer::getName;
    MutableList<String> customerNames = null;  // this.company.getCustomers()...

    var expectedNames = List.of("Fred", "Mary", "Bill");
    Assert.assertEquals(expectedNames, customerNames);
}
```
The latter solution which most developers have been learning about for a while now is only available as of Java 9.

**Comment by mohrezaei** [comment]
@donraab typo: your code examples are identical!
(You probably know this, but I'll mention it: for code this long, putting `java` after the three starting ticks will color code it)

**Comment by donraab** [comment]
Thanks @mohrezaei I usually just highlight with the angle brackets so thanks for the tip.

The code is not identical but is very close:

```Java
var expectedNames1 = Lists.mutable.with("Fred", "Mary", "Bill");
var expectedNames2 = Lists.immutable.with("Fred", "Mary", "Bill");
var expectedNames3 = List.of("Fred", "Mary", "Bill");
```
The code with explicit types would be:
```Java
MutableList<String> expectedNames1 = Lists.mutable.with("Fred", "Mary", "Bill");
ImmutableList<String expectedNames2 = Lists.immutable.with("Fred", "Mary", "Bill");
List<String> expectedNames3 = List.of("Fred", "Mary", "Bill");
```

**Comment by donraab** [comment]
[Exercise 4](https://github.com/eclipse/eclipse-collections-kata/blob/master/pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java#L50) of the Pet Kata has more usages of `var` outside of the expected values. The benefits here are subtle. On the one hand, it removes some noise and makes it easier to refactor from JDK types to Eclipse Collections types by removing the need to delete and replace the types. On the other hand, it may cause the developer to show the type by using `Alt-Enter`. This may help educate some students on determining when `var` is useful and when it is not.
