### ISSUE TITLE
Upgrade katas to Eclipse Collections 11.0.0.M3

### ISSUE THREAD

**Issue by donraab** [eclipse/eclipse-collections-kata#188]

**Comment by ashutosh887** [comment]
Should I work on it?
@donraab

**Comment by praneethjreddy** [comment]
@donraab I would love to work on this issue. Thank you

**Comment by RamVaidya** [comment]
@donraab If this is still available, I would like to tackle this as my first issue.

**Comment by RamVaidya** [comment]
@donraab ... I'm available now.

**Comment by donraab** [comment]
Assigned the ticket to you @RamVaidya. Will look out for PR tomorrow. Thanks!

**Comment by RamVaidya** [comment]
PR is ready.
