### ISSUE TITLE
BUG: converter-method-kata RichIterableToCollectionsTest#toStack() assertion always failure

### ISSUE THREAD

**Issue by hu-chia** [eclipse/eclipse-collections-kata#248]
https://github.com/eclipse/eclipse-collections-kata/blob/97fc3f29ebe6b281499438d597e233d7c421d089/converter-method-kata/src/test/java/org/eclipse/collections/convertermethodkata/RichIterableToCollectionsTest.java#L86

this should be: 
```java
        Assertions.assertEquals(list.toReversed(), stack.pop(3));
```

**Comment by donraab** [comment]
Hi @guyeu, this is a kata, so the code is left broken intentionally. The code you have provided would be solving the kata, and matches the code in the solutions module so your solution would be correct. Hope this helps.

https://github.com/eclipse/eclipse-collections-kata/blob/master/converter-method-kata-solutions/src/test/java/org/eclipse/collections/convertermethodkata/RichIterableToCollectionsTest.java#L79
