### ISSUE TITLE
How does `AbstractMutableBagIterable.topOccurences(int n)` work?

### ISSUE THREAD

**Issue by dxxvi** [eclipse/eclipse-collections-kata#270]
The code I see is:
```java
int keySize = Math.min(n, this.sizeDistinct());
MutableList<ObjectIntPair<T>> sorted = this.toListWithOccurrences().sortThisByInt(function);
MutableList<ObjectIntPair<T>> results = sorted.subList(0, keySize).toList();
```
If `this.toListWithOccurrences()` returns 100 pairs `(100 /*number of occurrencies*/, Object)`, `(1, Object)`, ... and to pickup the top 3 pairs, we have to sort all 100 pairs? If that's true, it's quite inefficient in this case. If that's untrue, how does it work for this case?

**Comment by donraab** [comment]
Hi @dxxvi, if you would like to propose or contribute a more efficient implementation for `topOccurrences` then the correct place to create the issue would be the Eclipse Collections repo. Thanks!

https://github.com/eclipse/eclipse-collections

**Comment by dxxvi** [comment]
@donraab I have no idea how to create a PR. I work with private git only where I create a branch and create a PR to merge that branch to master. It must be different with a public git like github where I cannot create a branch.

**Comment by donraab** [comment]
Hi @dxxvi, you can start by creating an issue and getting feedback and suggestions from EC committers. After that I would recommend reading the contributing guide for Eclipse Collections linked below.

https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md

There is a link to a separate guide to working with GitHub.

https://github.com/eclipse/eclipse-collections/wiki/Working-with-GitHub
