### ISSUE TITLE
Upgrade Eclipse Collections version

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections-kata#282]
The current Eclipse Collections (org.eclipse.collections:eclipse-collections-api and org.eclipse.collections:eclipse-collections) version is 11.1.0. Upgrade it to 12.0.0.M3.

**Comment by jinjin1919** [comment]
Can I have this issue assigned to me? thanks

**Comment by prathasirisha** [comment]
Closing the issue as this was completed
