### ISSUE TITLE
Add tag to unit tests in Haiku and Wordle kata

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections-kata#283]
Add tag "KATA" to the exercises in haiku-kata and wordle-kata to keep it consistent with other katas. 

Candy Kata example [here](https://github.com/eclipse/eclipse-collections-kata/blob/master/candy-kata/src/test/java/org/eclipse/collections/candykata/CandyKataTest.java#L36). Similarly, add tag KATA to [haiku-kata tests](https://github.com/eclipse/eclipse-collections-kata/tree/master/haiku-kata/src/test/java/org/eclipse/collections/haikukata) and [wordle-kata tests](https://github.com/eclipse/eclipse-collections-kata/tree/master/wordle-kata/src/test/java/org/eclipse/collections/wordlekata).

**Comment by ivalkshfoeif** [comment]
Hi @prathasirisha, I'd like to work on this issue. I'm GHC 2023 OSD attendee - Muxing Lin.

**Comment by j-emily-tso** [comment]
Not sure if this is still open, but I can work on this one (GHC 2023 attendee Jialin Tso)
