### ISSUE TITLE
Add implementation to TextProcessorEC.getHaikuAsCharAdapter() for haiku-kata-solutions module

### ISSUE THREAD

**Issue by rzrobin213** [eclipse/eclipse-collections-kata#286]
The method `getHaikuAsCharAdapter()` in the `TextProcessorEC` class for the [haiku-kata-solutions](https://github.com/eclipse/eclipse-collections-kata/tree/52070f7651667c27e974e45eea2cce4309345530/haiku-kata-solutions) module is not yet implemented. Follow the TODOs and hints given in the [method](https://github.com/eclipse/eclipse-collections-kata/blob/52070f7651667c27e974e45eea2cce4309345530/haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorEC.java#L36). Please do not add solutions to the non-solution modules. Make sure to adhere to our [contribution guide](https://github.com/eclipse/eclipse-collections-kata/blob/52070f7651667c27e974e45eea2cce4309345530/CONTRIBUTING.md).

Please note that this issue is created for GHC 2023 Open Source Day, thus priority will be given to the attendees of this event. After the event, this issue will be open to anyone.

**Comment by harshitha-ravi** [comment]
@prathasirisha - I am GHC 23 attendee, and would like to take up this issue.

**Comment by donraab** [comment]
Thanks for volunteering @harshitha-ravi. I've assigned the issue to you.

**Comment by harshitha-ravi** [comment]
@prathasirisha - Can you please check now? I updated the commit message.
