### ISSUE TITLE
Add implementation to TextProcessorJDK.getHaikuAsChars() for haiku-kata-solutions module

### ISSUE THREAD

**Issue by rzrobin213** [eclipse/eclipse-collections-kata#292]
The method `getHaikuAsChars()` in the `TextProcessorJDK` class for the [haiku-kata-solutions](https://github.com/eclipse/eclipse-collections-kata/tree/52070f7651667c27e974e45eea2cce4309345530/haiku-kata-solutions) module is not yet implemented. Follow the TODOs and hints given in the [method](https://github.com/eclipse/eclipse-collections-kata/blob/52070f7651667c27e974e45eea2cce4309345530/haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorJDK.java#L30). Please do not add solutions to the non-solution modules. Make sure to adhere to our [contribution guide](https://github.com/eclipse/eclipse-collections-kata/blob/52070f7651667c27e974e45eea2cce4309345530/CONTRIBUTING.md).

Please note that this issue is created for GHC 2023 Open Source Day, thus priority will be given to the attendees of this event. After the event, this issue will be open to anyone.

**Comment by bhsingla** [comment]
Hi @prathasirisha, could you please assign this issue to me.

**Comment by chuchugo** [comment]
Hi @prathasirisha， May I work on this issue?

**Comment by NiveditaMishraCoding** [comment]
I have fixed this issue in PR: https://github.com/eclipse/eclipse-collections-kata/pull/323/

**Comment by prathasirisha** [comment]
Closed as this is completed
