### ISSUE TITLE
Typo in hint of TextProcessorJDK.topLetters() in both haiku-kata and haiku-kata-solutions module

### ISSUE THREAD

**Issue by rzrobin213** [eclipse/eclipse-collections-kata#299]
In the hint of TextProcessorJDK.topLetters() for both [haiku-kata](https://github.com/eclipse/eclipse-collections-kata/blob/master/haiku-kata/src/main/java/org/eclipse/collections/haikukata/TextProcessorJDK.java#L42) and [haiku-kata-solutions](https://github.com/eclipse/eclipse-collections-kata/blob/master/haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorJDK.java#L42) module, there is a spelling error. The text should be: 

`// Hint: Also look at Collectors.groupingBy, Collectors.counting`

Please note that this issue is created for GHC 2023 Open Source Day, thus priority will be given to the attendees of this event. After the event, this issue will be open to anyone.

**Comment by ssoyeee** [comment]
Hi, can I be assigned to this issue? I would like to take up this.
