### ISSUE TITLE
Update slides.md in api-design to reflect the correct years of development

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections-kata#302]
Update [slides.md#what-is-eclipse-collections](https://github.com/eclipse/eclipse-collections-kata/blob/master/docs/api-design/slides.md#what-is-eclipse-collections) to reflect the correct years of development.  It should read: 18+ years of development. 

Please note that this issue is created for GHC 2023 Open Source Day, thus priority will be given to the attendees of this event. After the event, this issue will be open to anyone.

**Comment by LavanyaGopal** [comment]
Hello, 

Can I be assigned to this?
