### ISSUE TITLE
Update maven-surefire-plugin version

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections-kata#304]
Update maven-surefire-plugin to the latest available version and ensure all checks/builds go to success. 

Please note that this issue is created for GHC 2023 Open Source Day, thus priority will be given to the attendees of this event. After the event, this issue will be open to anyone.

**Comment by jay9dev** [comment]
Assigning this to Jayasri

**Comment by jay9dev** [comment]
@prathasirisha : I am GHC 23 attendee. I would like to work on this issue.

**Comment by zhiyiyi** [comment]
I would like to work on this issue if it's still open.
