### ISSUE TITLE
Remove unused imports in LineItem class in solutions module and in kata

### ISSUE THREAD

**Issue by prathasirisha** [eclipse/eclipse-collections-kata#306]
Remove unused imports in LineItem class in company-kata and company-kata-solutions.

Please note that this issue is created for GHC 2023 Open Source Day, thus priority will be given to the attendees of this event. After the event, this issue will be open to anyone.

**Comment by MandyMeindersma** [comment]
could you assign me :)

**Comment by MandyMeindersma** [comment]
I have signed the agreement
